### ISSUE TITLE
Does not work with Laravel 5

### ISSUE THREAD

**Issue by tomhatzer** [nerdial/LaravelCRUD#1]
Hi there!

Awesome work you did with laravel-crud. Is it possible to make this Laravel 5 ready?

Thank you very much!

Best wishes
Tom

**Comment by tomhatzer** [comment]
Ok, got the files ready... I don't know if it's ok how I did it, but it works. Quick and dirty :)

I've created a fork of your repo. Just have a look right here: https://github.com/tomhatzer/laravel5-crud

**Comment by chadsaun** [comment]
tomhatzer - I tried your first step of `php artisan make:console CrudMock --command=crud:mock` and I get this error `Console command already exists!`

Any ideas?

P.S. Your fork doesn't have a place for issues.

**Comment by nerdial** [comment]
@tomhatzer  I guess your fork repo does not work properly .. . I will check it out.

**Comment by nerdial** [comment]
@chadsaun  I dont think you need to execute any command in terminal
just try to add commands to app/Console/Commands/Kernel.php like below 

```
protected $commands = [
    'App\Console\Commands\CrudMake',
    'App\Console\Commands\CrudMock',
    'App\Console\Commands\Inspire',
];
```

**Comment by nerdial** [comment]
In Laravel 5 a lot of  things have been changed . I mention those changes that  have affected crud generator .
1. There is no model folder anymore so we have to create a Folder for that. i believe "Models" must be appropriate for it. 
2. we have to define some new namespaces in each controller we make .. 
3.  illuminate/html  package has been remove from core , so first we have to install the package and add the package to Provider and Aliases in config/app.php
s.th like this 
http://shems.co/blog/laravel-5-0-html-form-facades/

**Comment by tomhatzer** [comment]
@chadsaun I'm sorry, I'm still working on it and did not have time to upload the working version. Will do so in the next few days. - Issues should now be working in my fork, forgot to add them.

@vahidstar Thank you very much for your input! I'll use it to build a working version :)

Thank you very much to both of you!
